# Generated by Django 3.2 on 2024-08-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
