# Generated by Django 3.2 on 2024-08-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_poll_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='name',
            new_name='title',
        ),
    ]
