# Generated by Django 3.2 on 2024-08-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20240819_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='poll',
            name='show_result',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Show result after vote?'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='collect_email',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Do you want to collect email?'),
        ),
    ]
