# Generated by Django 3.2 on 2024-08-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20240820_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
