# Generated by Django 3.2 on 2024-08-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20240820_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='slug',
        ),
    ]
