# Generated by Django 3.2 on 2024-08-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_remove_poll_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='poll',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Want to show in homepage?'),
        ),
    ]
